### ISSUE TITLE
Not tolerant for decoding input without EOD

### ISSUE THREAD

**Issue by jetic83** [pgodwin/OcfLzw#1]
I had some trouble with some images which have slight errors: they do not have EOD.

The `Decode(Stream compressedInput, Stream output)` function will throw an exception then (`Error: data is null`).

When I just quit the function, the decoding works well. Therefore, I propose to just insert a check for if the input is at its end (without EOD).

**Comment by pgodwin** [comment]
Thanks for the pull request. I'll review it this week. 
I have an actively worked on version internally at work so need to see if I'm able to publish an update here.
