### ISSUE TITLE
Huge blob debugging

### ISSUE THREAD

**Issue by rollend** [pgodwin/OcfLzw#3]
Dear Author, thank you indeed for this well developed implementation. Nice and quick. 
I am not sure it was my fault of implementation or it is not expected to work for huge blob. 
Actually huge blob decoded can not result in usable contents. Blob sequence 1 is decoded correctly, nice and tidy. But when I attached with further sequences. Except first part, it went messy. 
Do you still following up? Or do you have any hints? 
I do appreciate if you have any hints. 
Regards,
Shen

**Comment by pgodwin** [comment]
Hi Shen. 

I've not had any issues with large values with this code. 

If these are out of a Cerner product, there is terminator at the end of each blob which needs to be removed. I can't provide the code for this here (as I don't own the rights as it was written for my employer) but this is the value I'm looking for and removing when combining values.
```c#
 static readonly char[] ocf_blob_eof = ("ocf_blob\0").ToCharArray();
```

Hope that helps!
