### ISSUE TITLE
SQL CLR

### ISSUE THREAD

**Issue by thegoatherder** [pgodwin/OcfLzw#4]
I'm delighted to have found this library. Is it relatively easy to build into SQL CLR do you know? Or as an SSIS script component? I need to extract RTF document data from a Cerner Millennium database...

**Comment by pgodwin** [comment]
Yes - I use it in a SQL CLR. The code will run in a [`SAFE` CLR environment](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-ver16). Note that the functionality has changed in SQL 2017.

You could also reference this library in an SSIS Script Transformation and decode values that way. 

If you wanted to be super awesome, you could turn it into a custom [PipelineComponent](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dts.pipeline.pipelinecomponent?view=sqlserver-2019).
